// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDate;
use serde::Serialize;
#[derive(Queryable, Debug)]
pub struct Channel {
    pub id: i32,
    pub name: String,
    pub allowed_users: i32,
    pub allowed_roles: String,
}

#[derive(Queryable, Debug)]
pub struct Server {
    pub id: i32,
    pub name: String,
    pub created_at: NaiveDate,
    pub users: i32,
    pub channels: i32,
    pub settings: i32,
}

#[derive(Queryable, Debug)]
pub struct ServerJoin {
    pub id: i32,
    pub user_id: i32,
    pub server_id: i32,
    pub joined_at: NaiveDate,
    pub settings: i32,
}

#[derive(Queryable, Debug)]
pub struct ServerRole {
    pub id: i32,
    pub server_id: i32,
    pub name: String,
    pub is_admin: bool,
}

#[derive(Queryable, Debug)]
pub struct ServerSetting {
    pub id: i32,
    pub roles: String,
}

#[derive(Queryable, Debug, Serialize)]
pub struct User {
    pub id: i32,
    pub username: String,
    pub email: String,
    pub name: String,
    pub password: String,
    pub created_at: Option<NaiveDate>,
    pub updated_at: Option<NaiveDate>,
}

#[derive(Queryable, Debug)]
pub struct UserServerSetting {
    pub id: i32,
    pub roles: String,
}